### ISSUE TITLE
Json切り分け1

### ISSUE THREAD

**Issue by inouetaka** [esaki01/kaggle-tmdb#3]
Jsonの値を別カラムで作成

・genres
・belongs_to_collection
・Keywords
・production_companies

**Comment by esaki01** [comment]
やっぱ配列は半角スペースじゃなくてカンマで区切ったほうが良さそう...
production_companiesとか1単語内で半角スペース結構使ってる...

**Comment by esaki01** [comment]
これ修正しました↑
